/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package unatec.ads.ess.aplicacao;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author user
 */

@ApplicationPath("/agenda")
public class Aplicacao extends Application{

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        Class jsonProvider = null;
        try {
            jsonProvider = Class.forName("org.glassfish.jersey.jackson.JacksonFeature");
            // Class jsonProvider = Class.forName("org.glassfish.jersey.moxy.json.MoxyJsonFeature");
            /*Class jsonProvider = Class.forName("org.glassfish.jersey.jettison.JettisonFeature");
            resources.add(jsonProvider);*/
        } catch (ClassNotFoundException ex) {
            try{
                jsonProvider = Class.forName("org.glassfish.jersey.moxy.json.MoxyJsonFeature");
            }catch (Exception ex2) {
                try{
                    jsonProvider = Class.forName("org.glassfish.jersey.jettison.JettisonFeature");
                }catch(Exception ex3){
                    java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex3);
                }
            }
        }
        if(jsonProvider != null)
            resources.add(jsonProvider);
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(unatec.ads.ess.servicos.ServicoEquipamento.class);
        resources.add(unatec.ads.ess.servicos.ServicoSalas.class);
        resources.add(unatec.ads.ess.servicos.ServicoEspecialidades.class);
        resources.add(unatec.ads.ess.servicos.ServicoMedicos.class);
        /*resources.add(unatec.ads.ess.servicos.ServicoMateriais.class);
        resources.add(unatec.ads.ess.servicos.ServicoProcedimento.class);
        resources.add(unatec.ads.ess.servicos.ServicoSalas.class);
        resources.add(unatec.ads.ess.servicos.ServicosLogin.class);*/
    }
    
}
