package unatec.ads.ess.entidade;
// Generated 21/10/2013 05:53:49 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlRootElement;




/**
 * Equipamento generated by hbm2java
 */

@XmlRootElement
public class Equipamento  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private int qtd;

    public Equipamento() {
    }

    public Equipamento(String descricao, int qtd) {
       this.descricao = descricao;
       this.qtd = qtd;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getQtd() {
        return this.qtd;
    }
    
    public void setQtd(int qtd) {
        this.qtd = qtd;
    }




}


