package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Equipamentos generated by hbm2java
 */
@XmlRootElement
public class Equipamentos  implements java.io.Serializable {


     private Integer equipamentoId;
     private String equipamentoDescricao;
     private Integer equipamentoQtdeDisponivel;
     private Set equipamentosAgendamentoses = new HashSet(0);

    public Equipamentos() {
    }

    public Equipamentos(String equipamentoDescricao, Integer equipamentoQtdeDisponivel, Set equipamentosAgendamentoses) {
       this.equipamentoDescricao = equipamentoDescricao;
       this.equipamentoQtdeDisponivel = equipamentoQtdeDisponivel;
       this.equipamentosAgendamentoses = equipamentosAgendamentoses;
    }
   
    public Integer getEquipamentoId() {
        return this.equipamentoId;
    }
    
    public void setEquipamentoId(Integer equipamentoId) {
        this.equipamentoId = equipamentoId;
    }
    public String getEquipamentoDescricao() {
        return this.equipamentoDescricao;
    }
    
    public void setEquipamentoDescricao(String equipamentoDescricao) {
        this.equipamentoDescricao = equipamentoDescricao;
    }
    public Integer getEquipamentoQtdeDisponivel() {
        return this.equipamentoQtdeDisponivel;
    }
    
    public void setEquipamentoQtdeDisponivel(Integer equipamentoQtdeDisponivel) {
        this.equipamentoQtdeDisponivel = equipamentoQtdeDisponivel;
    }
    public Set getEquipamentosAgendamentoses() {
        return this.equipamentosAgendamentoses;
    }
    
    public void setEquipamentosAgendamentoses(Set equipamentosAgendamentoses) {
        this.equipamentosAgendamentoses = equipamentosAgendamentoses;
    }




}


