package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlRootElement;




/**
 * EquipamentosAgendamentosId generated by hbm2java
 */
@XmlRootElement
public class EquipamentosAgendamentosId  implements java.io.Serializable {


     private int agendamentoId;
     private int equipamentoId;

    public EquipamentosAgendamentosId() {
    }

    public EquipamentosAgendamentosId(int agendamentoId, int equipamentoId) {
       this.agendamentoId = agendamentoId;
       this.equipamentoId = equipamentoId;
    }
   
    public int getAgendamentoId() {
        return this.agendamentoId;
    }
    
    public void setAgendamentoId(int agendamentoId) {
        this.agendamentoId = agendamentoId;
    }
    public int getEquipamentoId() {
        return this.equipamentoId;
    }
    
    public void setEquipamentoId(int equipamentoId) {
        this.equipamentoId = equipamentoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EquipamentosAgendamentosId) ) return false;
		 EquipamentosAgendamentosId castOther = ( EquipamentosAgendamentosId ) other; 
         
		 return (this.getAgendamentoId()==castOther.getAgendamentoId())
 && (this.getEquipamentoId()==castOther.getEquipamentoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAgendamentoId();
         result = 37 * result + this.getEquipamentoId();
         return result;
   }   


}


