package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidades generated by hbm2java
 */
public class Especialidades  implements java.io.Serializable {


     private Integer especialidadeId;
     private String especialidadeNome;
     private String especialidadeDescricao;
     private Set medicoses = new HashSet(0);

    public Especialidades() {
    }

    public Especialidades(String especialidadeNome, String especialidadeDescricao, Set medicoses) {
       this.especialidadeNome = especialidadeNome;
       this.especialidadeDescricao = especialidadeDescricao;
       this.medicoses = medicoses;
    }
   
    public Integer getEspecialidadeId() {
        return this.especialidadeId;
    }
    
    public void setEspecialidadeId(Integer especialidadeId) {
        this.especialidadeId = especialidadeId;
    }
    public String getEspecialidadeNome() {
        return this.especialidadeNome;
    }
    
    public void setEspecialidadeNome(String especialidadeNome) {
        this.especialidadeNome = especialidadeNome;
    }
    public String getEspecialidadeDescricao() {
        return this.especialidadeDescricao;
    }
    
    public void setEspecialidadeDescricao(String especialidadeDescricao) {
        this.especialidadeDescricao = especialidadeDescricao;
    }
    public Set getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set medicoses) {
        this.medicoses = medicoses;
    }




}


