package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlRootElement;




/**
 * MateriaisAgendamentos generated by hbm2java
 */
@XmlRootElement
public class MateriaisAgendamentos  implements java.io.Serializable {


     private MateriaisAgendamentosId id;
     private Materiais materiais;
     private Agendamentos agendamentos;
     private Integer materiaisAgendamentosQtde;

    public MateriaisAgendamentos() {
    }

	
    public MateriaisAgendamentos(MateriaisAgendamentosId id, Materiais materiais, Agendamentos agendamentos) {
        this.id = id;
        this.materiais = materiais;
        this.agendamentos = agendamentos;
    }
    public MateriaisAgendamentos(MateriaisAgendamentosId id, Materiais materiais, Agendamentos agendamentos, Integer materiaisAgendamentosQtde) {
       this.id = id;
       this.materiais = materiais;
       this.agendamentos = agendamentos;
       this.materiaisAgendamentosQtde = materiaisAgendamentosQtde;
    }
   
    public MateriaisAgendamentosId getId() {
        return this.id;
    }
    
    public void setId(MateriaisAgendamentosId id) {
        this.id = id;
    }
    public Materiais getMateriais() {
        return this.materiais;
    }
    
    public void setMateriais(Materiais materiais) {
        this.materiais = materiais;
    }
    public Agendamentos getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Agendamentos agendamentos) {
        this.agendamentos = agendamentos;
    }
    public Integer getMateriaisAgendamentosQtde() {
        return this.materiaisAgendamentosQtde;
    }
    
    public void setMateriaisAgendamentosQtde(Integer materiaisAgendamentosQtde) {
        this.materiaisAgendamentosQtde = materiaisAgendamentosQtde;
    }




}


