package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Materiais generated by hbm2java
 */
@XmlRootElement
public class Materiais  implements java.io.Serializable {


     private Integer materialId;
     private String materialDescricao;
     private Integer materialQtdeDisponivel;
     private Set materiaisAgendamentoses = new HashSet(0);

    public Materiais() {
    }

    public Materiais(String materialDescricao, Integer materialQtdeDisponivel, Set materiaisAgendamentoses) {
       this.materialDescricao = materialDescricao;
       this.materialQtdeDisponivel = materialQtdeDisponivel;
       this.materiaisAgendamentoses = materiaisAgendamentoses;
    }
   
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
    public String getMaterialDescricao() {
        return this.materialDescricao;
    }
    
    public void setMaterialDescricao(String materialDescricao) {
        this.materialDescricao = materialDescricao;
    }
    public Integer getMaterialQtdeDisponivel() {
        return this.materialQtdeDisponivel;
    }
    
    public void setMaterialQtdeDisponivel(Integer materialQtdeDisponivel) {
        this.materialQtdeDisponivel = materialQtdeDisponivel;
    }
    public Set getMateriaisAgendamentoses() {
        return this.materiaisAgendamentoses;
    }
    
    public void setMateriaisAgendamentoses(Set materiaisAgendamentoses) {
        this.materiaisAgendamentoses = materiaisAgendamentoses;
    }




}


