package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlRootElement;




/**
 * MateriaisAgendamentosId generated by hbm2java
 */
@XmlRootElement
public class MateriaisAgendamentosId  implements java.io.Serializable {


     private int agendamentoId;
     private int materialId;

    public MateriaisAgendamentosId() {
    }

    public MateriaisAgendamentosId(int agendamentoId, int materialId) {
       this.agendamentoId = agendamentoId;
       this.materialId = materialId;
    }
   
    public int getAgendamentoId() {
        return this.agendamentoId;
    }
    
    public void setAgendamentoId(int agendamentoId) {
        this.agendamentoId = agendamentoId;
    }
    public int getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(int materialId) {
        this.materialId = materialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MateriaisAgendamentosId) ) return false;
		 MateriaisAgendamentosId castOther = ( MateriaisAgendamentosId ) other; 
         
		 return (this.getAgendamentoId()==castOther.getAgendamentoId())
 && (this.getMaterialId()==castOther.getMaterialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAgendamentoId();
         result = 37 * result + this.getMaterialId();
         return result;
   }   


}


