package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Medicos generated by hbm2java
 */
@XmlRootElement
public class Medicos  implements java.io.Serializable {


     private Integer medicoId;
     private Pessoas pessoas;
     private Especialidades especialidades;
     private String medicoCrm;
     private Set agendamentoses = new HashSet(0);

    public Medicos() {
    }

	
    public Medicos(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Medicos(Pessoas pessoas, Especialidades especialidades, String medicoCrm, Set agendamentoses) {
       this.pessoas = pessoas;
       this.especialidades = especialidades;
       this.medicoCrm = medicoCrm;
       this.agendamentoses = agendamentoses;
    }
   
    public Integer getMedicoId() {
        return this.medicoId;
    }
    
    public void setMedicoId(Integer medicoId) {
        this.medicoId = medicoId;
    }
    public Pessoas getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Especialidades getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Especialidades especialidades) {
        this.especialidades = especialidades;
    }
    public String getMedicoCrm() {
        return this.medicoCrm;
    }
    
    public void setMedicoCrm(String medicoCrm) {
        this.medicoCrm = medicoCrm;
    }
    public Set getAgendamentoses() {
        return this.agendamentoses;
    }
    
    public void setAgendamentoses(Set agendamentoses) {
        this.agendamentoses = agendamentoses;
    }




}


