package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer pacienteId;
     private Pessoas pessoas;
     private Set agendamentoses = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Pacientes(Pessoas pessoas, Set agendamentoses) {
       this.pessoas = pessoas;
       this.agendamentoses = agendamentoses;
    }
   
    public Integer getPacienteId() {
        return this.pacienteId;
    }
    
    public void setPacienteId(Integer pacienteId) {
        this.pacienteId = pacienteId;
    }
    public Pessoas getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Set getAgendamentoses() {
        return this.agendamentoses;
    }
    
    public void setAgendamentoses(Set agendamentoses) {
        this.agendamentoses = agendamentoses;
    }




}


