package unatec.ads.ess.entidadeDao;
// Generated 29/10/2013 20:49:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Pessoas generated by hbm2java
 */
@XmlSeeAlso({Pacientes.class, Medicos.class, Administradores.class})
@XmlRootElement
public class Pessoas  implements java.io.Serializable {


     private Integer pessoaId;
     private String pessoaNome;
     private String pessoaEmail;
     private String pessoaTelefone;
     private String pessoaLogin;
     private String pessoaSenhaHash;
     private Set medicoses = new HashSet(0);
     private Set pacienteses = new HashSet(0);
     private Set administradoreses = new HashSet(0);

    public Pessoas() {
    }

    public Pessoas(String pessoaNome, String pessoaEmail, String pessoaTelefone, String pessoaLogin, String pessoaSenhaHash, Set medicoses, Set pacienteses, Set administradoreses) {
       this.pessoaNome = pessoaNome;
       this.pessoaEmail = pessoaEmail;
       this.pessoaTelefone = pessoaTelefone;
       this.pessoaLogin = pessoaLogin;
       this.pessoaSenhaHash = pessoaSenhaHash;
       this.medicoses = medicoses;
       this.pacienteses = pacienteses;
       this.administradoreses = administradoreses;
    }
   
    public Integer getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(Integer pessoaId) {
        this.pessoaId = pessoaId;
    }
    public String getPessoaNome() {
        return this.pessoaNome;
    }
    
    public void setPessoaNome(String pessoaNome) {
        this.pessoaNome = pessoaNome;
    }
    public String getPessoaEmail() {
        return this.pessoaEmail;
    }
    
    public void setPessoaEmail(String pessoaEmail) {
        this.pessoaEmail = pessoaEmail;
    }
    public String getPessoaTelefone() {
        return this.pessoaTelefone;
    }
    
    public void setPessoaTelefone(String pessoaTelefone) {
        this.pessoaTelefone = pessoaTelefone;
    }
    public String getPessoaLogin() {
        return this.pessoaLogin;
    }
    
    public void setPessoaLogin(String pessoaLogin) {
        this.pessoaLogin = pessoaLogin;
    }
    public String getPessoaSenhaHash() {
        return this.pessoaSenhaHash;
    }
    
    public void setPessoaSenhaHash(String pessoaSenhaHash) {
        this.pessoaSenhaHash = pessoaSenhaHash;
    }
    public Set getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set medicoses) {
        this.medicoses = medicoses;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }
    public Set getAdministradoreses() {
        return this.administradoreses;
    }
    
    public void setAdministradoreses(Set administradoreses) {
        this.administradoreses = administradoreses;
    }




}


